### ISSUE TITLE
Compound operators error on table fields

### ISSUE THREAD

**Issue by linuxdaemon** [Vexatos/Selene#1]
This code:
```lua
local var1 = 5
var1 += 2

local t = {a=4}
t.a += 3

```
errors when attempting to increment `t.a`

### Using
OpenOS 1.6.7
selene-openos 0.1.0.4
Lua 5.3

**Comment by Vexatos** [comment]
Thank you very much. I'll look into it.

**Comment by Vexatos** [comment]
More complex things like `a:foo("bar").baz += 4` still won't work but I think I can live with that.
